### ISSUE TITLE
Which is the official demo API? / Quality of examples

### ISSUE THREAD

**Issue by o-st** [admin-shell-io/questions-and-answers#114]
I am currently looking at two servers hosting AAS APIs:

1. v3.admin-shell-io.com
2. admin-shell-io.com/5001/

It could be me misunderstanding the AAS specification, but:
- calling GetAllShells endpoint on the first server shows multiple shells with the same identifier (`www.company.com/ids/aas/2520_6010_8091_1277`), which should not be possible according to the spec
- calling GetAllShells endpoint on the second server shows shells which do not have an `id` property, but have an `identification` object in their JSON serialization instead. I cannot find information about this object anywhere in the v3 specs. It is also not part of the generated meta-model code of the [AAS Core](https://github.com/aas-core-works/aas-core3.0-typescript/tree/main) project

Since both sources contain examples which do not adhere to the standard, I ask myself where I could find an up-to-date demo API following the standard.

**Comment by StenGruener** [comment]
This is tricky, the first one is probably just some bug of contained data where the backend is not checking consistency.

Try those:
- https://backend2.dpp40-2-v2.industrialdigitaltwin.org/shells/
- https://c1.api.wago.com/smartdata-aas-env/shells/
- https://mnestix-api-prod.azurewebsites.net/repo/shells/

Last two should be basyx while first one aasx-server

**Comment by o-st** [comment]
Hi @StenGruener!

Thank you very much for your answer! Looking at the WAGO repository, I see, that it supports the `GetAllShells` endpoint from the Shell Repository service. 

What is strange is, that - in order to get a submodel for a shell - you cannot use the `GetSubmodel` (`/shells/:aasIdBase64/submodels/:submodelIdBase64`) endpoint from the Shell Repository API. Instead you have to use the `GetSubmodelById` (`/submodels/:submodelIdBase64`) endpoint from the Submodel Repository API. 

I am also not able to retrieve the self-description endpoint (`GetDescription`) at `/description` for the WAGO server. 

What is the reason for this?

Thank you again for your time!

**Comment by StenGruener** [comment]
hi,

for the second questions I cannot talk for WAGO, since i am not associated with them and everything would be a wild guess. I'd propose you try out some basyx demos to see if its the case.

The first one is generic to AAS resolution process, see aas spec part 2: 
![image](https://github.com/user-attachments/assets/a57b8754-9b9c-4362-b853-611437e9d666)

The reason is, that submodels are deployment units and can be scattered across different hosting locations. Therefore the AAS just knows IDs of submodels contained into it, but they must not be on the same REST endpoint.
