### ISSUE TITLE
Question on how to connect OPC UA array data with AAS

### ISSUE THREAD

**Issue by andyrose-kr** [admin-shell-io/questions-and-answers#45]
I participated in a pilot project (KOSMO, Nestfield) in Korea to collect data by connecting OPC UA data from field devices to AAS in the cloud. During the project, I found out that there are many array type OPC UA data are defined in field devices. However, when creating AAS using the Aasx package explorer, I couldn't find a way on how to define array type data as a property.

From an AAS point of view in my project, the array data must be accessible as a single property by itself, and at the same time, the elements contained in the array must be individually identifiable.

It seems that all elements included in the array have the same semantic ID.  If both idShort and ID of each elements are the same, it seems that there will be a problem in identifying elements individually.

So my question is, is there a standardized method or guide that can be applied when creating array-type properties in AAS?

**Comment by StenGruener** [comment]
Short-term solution:
"Blob"-element e.g. "[1,2,3,4,5]" as a "serialized" JSON-value format (see upcoming time series submodel template). The data types of array's content, e.g. string, float or integer, can be defined using custom semantic ID of the submodel element.

Design decisions: take "Blob" instead of String in order not to overload generic UIs with representation of possibly long arrays.

Mid- to long-term solution:
A change to metamodel of the AAS is required. Birgit and Michael will take it to sub working group AAS of AG1 for further discussions
